//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepasGeneral.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURACIO
    {
        public int ID { get; set; }
        public Nullable<bool> SUMES { get; set; }
        public Nullable<bool> RESTES { get; set; }
        public Nullable<bool> MULTIPLICACIONS { get; set; }
    }
}
